comment:
  layout: "header, diff, flags, files" # show flag info in the PR comment
flag_management:
  default_rules: # default rules that will be inherited by all flags
    statuses:
      - type: project # in this case every flag that doens't have a status defined will have a project type
        target: auto
        threshold: 5%
        branches:
          - master
  individual_flags:
    - name: backend-apis # only Golang backend APIs
      paths:
        - "webv2/**"
        - "!webv2/webCmd.go"
      statuses: # each component has its own status and corresponding configuration
        - type: project
          target: auto
    - name: backend-library # only library code
      paths:
        - "!webv2/**"
        - "!ui/**"
        - "!cmd/**"
      statuses: # each component has its own status and corresponding configuration
        - type: project
          target: auto
    - name: cli # only the CLI
      paths:
        - "cmd/**"
        - "webv2/webCmd.go"
      statuses: # each component has its own status and corresponding configuration
        - type: project
          target: auto
    - name: frontend # only frontend components
      paths:
        - ui/**
      statuses: # the core component has its own statuses
        - type: project
          target: auto
ignore:
  - ".docker"
  - ".github"
  - "docs"
